### ISSUE TITLE
Recycling Project : W3C Error on page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#108]
Recycling Project
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcommunitypod.stage.titanweb.com.au%2Fabout-us%2Frecycling-project%2F

**Comment by bukssaayman** [comment]
The dropdown for Zip/Postal code has a default value <option value='' selected='selected'></option> that is empty. This is part of the Gravity forms plugin. I cannot change this.
