### ISSUE TITLE
Product List/Product Single : Images are cropped or lose their ratio. Please refer to implementation standard.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#110]
Refer also this sample site: http://aliceclothing-2016.stage.titanweb.com.au/product-category/fabric-packs/

![105](https://cloud.githubusercontent.com/assets/18256652/15279170/165d1d72-1b54-11e6-80d8-bf2cf351ad39.png)

**Comment by euveng** [comment]
Fixed, it can now accommodate very excessively wide images, but excessively high images will overflow vertically. Is this ok?

**Comment by iteano** [comment]
No its not. Roselie sent you an email about woocommerce website. Please see mail transition. Thanks.

**Comment by euveng** [comment]
Fixed, please check if it's ok now.

**Comment by iteano** [comment]
You did right on the product list, but on the product single please see attached for the problem.
![b](https://cloud.githubusercontent.com/assets/18256652/15379865/bd1f9670-1da3-11e6-8f26-583cb9fff153.png)

**Comment by euveng** [comment]
Fixed.
