### ISSUE TITLE
About The Coffee : Inconsistent page layout from design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#120]
![115](https://cloud.githubusercontent.com/assets/18256652/15281772/be833b3c-1b70-11e6-8617-e954dcee46d5.png)

**Comment by euveng** [comment]
If an image has been uploaded as the featured image, it will be assigned to the col-3 to the left of the content. This needs to be consistent throughout all pages. If a full-width image is desired, upload it within the text editor.
