### ISSUE TITLE
Homepage-Leaderboard : Inconsistent iField between frontend and design. Just want to clarify which of the two iFields is correct.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#22]
Note:
1. If the frontend got the correct ifield please let us know where can we find it from the backend.
2. And, If the design is correct implement it on the frontend and still let us know where it is located from the backend. Thanks.

![22](https://cloud.githubusercontent.com/assets/18256652/15002431/aeca6950-11d3-11e6-9ac3-8d1ecea3af37.png)

**Comment by bukssaayman** [comment]
The iFrame on stage is correct. It's an ACF option on the home page.
