### ISSUE TITLE
Charities : Charities page has no design. Please add design to the page according to scope.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#27]
![27](https://cloud.githubusercontent.com/assets/18256652/15004216/db8c823a-11e6-11e6-8be1-ae4c22022a58.png)

**Comment by bukssaayman** [comment]
The charities page you are referring to that is empty is a plain content page. The charities page the project scope refers to is under Ros's Hub -> Dr Ross's Charities.

**Comment by iteano** [comment]
Changing the label of this to wontfix, obviously the scope didn't state that charities i am referring for is of from Dr Ros's Charity.
