### ISSUE TITLE
General-Inner Pages : Breadcrumbs are not functional. Observed on submenu and inner pages.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#28]
![29](https://cloud.githubusercontent.com/assets/18256652/15004292/d492fa3a-11e7-11e6-92b3-a14b652b9333.png)

**Comment by iteano** [comment]
![28a](https://cloud.githubusercontent.com/assets/18256652/15006289/b8a90d2c-1201-11e6-9818-1cf6d1958808.png)

**Comment by bukssaayman** [comment]
Fixed.
