### ISSUE TITLE
Recycling Project : Please advise if the design is correct since the scope doesnt clearly states and there is no psd design for the page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#29]
Note: If it is already the correct design of the page, please fix the layout. There were some missing input fields.

![30](https://cloud.githubusercontent.com/assets/18256652/15004433/757cd4ec-11e9-11e6-9ee1-0b058acc2002.png)

**Comment by bukssaayman** [comment]
Yes, this is correct according to what is on stage. The client requested more changes to this page.
