### ISSUE TITLE
Submenu pages : Inconsisten submenu pages between About Us and Ros's Hub menu. Please advise which one is correct, the one with banner or the one which don't have.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#31]
![31](https://cloud.githubusercontent.com/assets/18256652/15004711/f4e8e16e-11ec-11e6-8f13-1427471f468f.png)

**Comment by bukssaayman** [comment]
The pages are content managed, the banners are set per page at the bottom of the wp-admin edit screen. I've added the banner for this specific page.
