### ISSUE TITLE
Product Single-Gallery : Multiple slider observed.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#40]
![40](https://cloud.githubusercontent.com/assets/18256652/15007908/eceb09f2-120e-11e6-9bf1-0ce30428b3a4.png)

Please refer this site for product single gallery: 
http://aliceclothing-2016.stage.titanweb.com.au/our-products/polo-shirts/product-9/

**Comment by euveng** [comment]
Unable to reproduce issue, please advise test conditions.

**Comment by iteano** [comment]
Not fixed as verified.

**Comment by euveng** [comment]
Please check again, this time it should be alright.

**Comment by iteano** [comment]
Still not fixed.

**Comment by bukssaayman** [comment]
I can't see the sub-slider anywhere on any products. If you see it's still not fixed, please comment with a URL to where it is showing.

**Comment by iteano** [comment]
For reference,please follow the fancy box of this product. Thanks.
http://aliceclothing-2016.stage.titanweb.com.au/our-products/skirts/24016-ladies-waisted-pencil-skirt-5/

**Comment by bukssaayman** [comment]
Fixed. I asked Ev to remove the filename that was displayed top left and minimize the padding at the bottom between the image and the pop-up.
