### ISSUE TITLE
Product Listing : Paginate at 7 which inconsistent from design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#42]
![42](https://cloud.githubusercontent.com/assets/18256652/15008667/7c2e3a4e-1214-11e6-8157-6b0e704ee3c2.png)

**Comment by bukssaayman** [comment]
Pagination for shop items in Woocommerce is controlled by a setting in wp-admin. Settings --> Reading -->Blog pages show at most. That is a Woocommerce/WordPress setting.

**Comment by iteano** [comment]
As per standard please refer to this link: https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/pagination-links.
