### ISSUE TITLE
Product Listing : Should display if no title and no product image set at the backend.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#45]
![45](https://cloud.githubusercontent.com/assets/18256652/15009288/227d7b32-1218-11e6-9c6a-6d63f4cab2fa.png)

**Comment by bukssaayman** [comment]
The description read that the product listing should display if no title and no product image set at the backend, which currently does happen. So I assume you meant it should NOT display if no title and no product image set? Woocommerce assigns a default image, so I changed it to not show if there is no title.
