### ISSUE TITLE
Cart : For variable product please align the attribute and the variation value.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#51]
![51](https://cloud.githubusercontent.com/assets/18256652/15034603/d5af0860-12a9-11e6-815c-6dc93caece87.png)

**Comment by euveng** [comment]
Unable to reproduce this, please advise testing conditions.

**Comment by iteano** [comment]
Set or add a variable product at the backend.
Add that variable product that you had made on the cart.

**Comment by euveng** [comment]
I have tested on ff and chrome and am unable to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/9030354/15309405/57ee5d80-1c19-11e6-9d8a-920c4446f039.png)

**Comment by iteano** [comment]
Fixed verified.
