### ISSUE TITLE
Ros's Hub : No image placeholder if featured image removed.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#54]
![54](https://cloud.githubusercontent.com/assets/18256652/15034901/93c5e23a-12ad-11e6-9a89-d38790628648.png)

**Comment by iteano** [comment]
Please note that this also occurs on all inner pages.

**Comment by bukssaayman** [comment]
I have changed it so that when the image is removed the text takes up the entire width of the page.
