### ISSUE TITLE
Who is Dr. Ros... : Add sidebar to make it consistent from its co-submenu pages from Ros's Hub menu.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#56]
![56](https://cloud.githubusercontent.com/assets/18256652/15034962/7cb7f762-12ae-11e6-9a53-764b2e3a59a0.png)

**Comment by bukssaayman** [comment]
This page was built using plain content page template which could have been used anywhere else on the site, therefore I could not add the side menu bar to that template. I had to create a brand new template to allow for this.
