### ISSUE TITLE
Ros's Hub-Submenu : Please remove the sidebar link that directs to its own page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#58]
![58](https://cloud.githubusercontent.com/assets/18256652/15035112/a0456b22-12b0-11e6-80ed-2a1d13a246d5.png)

**Comment by bukssaayman** [comment]
Fixed. As long as you are on the blog page or a single blog, you wont see the menu item for blog. Also if you are on the charities page or a single charity you wont see the Dr Ros's charities menu item.

**Comment by iteano** [comment]
Great. Thanks for fixing this.
