### ISSUE TITLE
Homepage - Buttons: Incorrect page link for buttons from banner and hompage content.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#6]
![6](https://cloud.githubusercontent.com/assets/18256652/14974037/77e6e5aa-1122-11e6-8fcb-c3b72c16f33a.png)

**Comment by bukssaayman** [comment]
Those buttons are completely content managed in wp-admin. At the time of going to QA, content wasn't uploaded, so I made them to go to google.com because I didn't know where they should link to. This isn't a bug.

**Comment by iteano** [comment]
Changing this to won't fix, since this is really a bug until final content will be provided.
