### ISSUE TITLE
Dr. Ros's Charities : Deleting the page content in the backend removes the listing at the frontend.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#62]
![62](https://cloud.githubusercontent.com/assets/18256652/15036550/09471f14-12c3-11e6-82c1-8a992bdfe9de.png)

**Comment by bukssaayman** [comment]
I don't think it's deleting the content that removed the charities. When I edited the page I see the page template was changed to "Default Template" it should be "Ros's Charities". You can delete the content and the charities still show when the correct page template is selected.
