### ISSUE TITLE
Banner-viewport size : Banner images are not responsive, it is cut when moving thru different viewport sizes.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#75]
Please refer to this site for the behavior of the banner when moving thru any viewport sizes.
http://aliceclothing-2016.stage.titanweb.com.au/

![75a](https://cloud.githubusercontent.com/assets/18256652/15037711/2686b884-12d0-11e6-926b-4dab37747b12.png)
![75](https://cloud.githubusercontent.com/assets/18256652/15037712/2a6c5e40-12d0-11e6-8184-61c312a3097b.png)

**Comment by euveng** [comment]
Fixed.
