### ISSUE TITLE
Leadin-viewport : Images are not responsive, at 1199px viewport size image clipped.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#76]
![76](https://cloud.githubusercontent.com/assets/18256652/15037881/659d21a6-12d1-11e6-84cf-3c7b0b03a61a.png)

**Comment by euveng** [comment]
This was done by setting the background-size to 'cover', to fit either max width or max height, to maintain the portrait image ratio. If not, there will be blank space below the image within the div if the image is more portrait than landscape, like attached. 
![image](https://cloud.githubusercontent.com/assets/9030354/15104082/6dfe833c-15e5-11e6-813b-6a906faadcdb.png)
