### ISSUE TITLE
Banner-viewport size : Buttons clipped at 320px viewport size.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#79]
Please refer to this site for the banner behavior at viewport.
http://aliceclothing-2016.stage.titanweb.com.au/

![79](https://cloud.githubusercontent.com/assets/18256652/15038171/06750aec-12d4-11e6-86dc-dff02cdc9cc8.png)

**Comment by euveng** [comment]
Fixed.
