### ISSUE TITLE
Hompage-viewport : Leaderboards text dropped at 320 viewport size.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#80]
![80](https://cloud.githubusercontent.com/assets/18256652/15038203/529bff52-12d4-11e6-83e9-992dc2210292.png)

**Comment by euveng** [comment]
What is the expected behaviour here?

**Comment by iteano** [comment]
Please reduce the font size of the Leaderboards text to be in one line and fits in the 320px viewport size.

**Comment by euveng** [comment]
Fixed.
