### ISSUE TITLE
Device Test - Homepage : Using iPod, background image did not fully cover the whole screen.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#82]
![82](https://cloud.githubusercontent.com/assets/18256652/15039188/60192d68-12dd-11e6-8481-d7ce526b936d.PNG)

**Comment by euveng** [comment]
This would actually depend on the iframed content - the current iframe is only test content and may not reflect the final content. I would suggest to wait for final iframe content before reviewing this issue again.

**Comment by iteano** [comment]
Waiting for the final iframe content.

**Comment by euveng** [comment]
Can this item be left pending while content is being uploaded?

**Comment by iteano** [comment]
Okay, we will verify this issue after the final content uploaded.

**Comment by euveng** [comment]
Hi, please check out the final page here http://www.communitypod.com.au/

The iframe looks to fit in the container nicely on ipod.
