### ISSUE TITLE
Homepage-W3C : Multiple errors on homepages.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#89]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcommunitypod.stage.titanweb.com.au%2F

![89](https://cloud.githubusercontent.com/assets/18256652/15063995/deb5e0b8-1381-11e6-81eb-3ad70ec16144.png)

**Comment by euveng** [comment]
Fixed.
