### ISSUE TITLE
About Us : W3C errors on the page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#90]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcommunitypod.stage.titanweb.com.au%2Fabout-us%2F

![90](https://cloud.githubusercontent.com/assets/18256652/15064024/3780f426-1382-11e6-9dfe-80f529ca6e5a.png)

**Comment by bukssaayman** [comment]
Fixed.
