### ISSUE TITLE
Checkout : Is the create an account section necessary?If not please remove.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#92]
It only requires a password which is misleading. There's a message says "If you are a returning customer please login at the top of the page.", how can we login we don't have an account yet and theres no page on the site for creating an account.

![92](https://cloud.githubusercontent.com/assets/18256652/15065392/bad65bae-1391-11e6-8ae9-f725fbd9e682.png)

**Comment by bukssaayman** [comment]
If you don't have an account, you click the button and it will create an account. Then next time you purchase you can log in.

You create the account there at that point of purchase.
