### ISSUE TITLE
Admin-Form : Please enable anti-spam honeypot of Product Enquiry and Recycling.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#94]
https://knowledgebase.titanweb.com.au/implementation/gravity-forms-implementation/enabling-gravity-forms-anti-spam-honeypot

![94](https://cloud.githubusercontent.com/assets/18256652/15277934/5ea14cd6-1b43-11e6-8423-a59aab9476cc.png)

**Comment by bukssaayman** [comment]
Fixed.
