### ISSUE TITLE
#igiveashot : Please display only 12 items as per design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#98]
![98](https://cloud.githubusercontent.com/assets/18256652/15278172/677b86c4-1b47-11e6-9877-d1af3f949f91.png)
![98a](https://cloud.githubusercontent.com/assets/18256652/15278179/8116b432-1b47-11e6-9df0-f78c0cd5b075.png)

**Comment by bukssaayman** [comment]
Fixed.
